#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: loram <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/10 21:57:54 by loram             #+#    #+#              #
#    Updated: 2019/09/22 20:50:01 by loram            ###   ########.fr        #
#                                                                              #
#******************************************************************************#


NAME = libft.a

SRC =	ft_atoi.c \
		ft_bzero.c \
		ft_istabeolsp.c \
		ft_itoa.c \
		ft_memalloc.c \
		ft_memccpy.c \
		ft_memchr.c \
		ft_memcmp.c \
		ft_memcpy.c \
		ft_memdel.c \
		ft_memmove.c \
		ft_memset.c \
		ft_putchar.c \
		ft_putchar_fd.c \
		ft_putendl.c \
		ft_putendl_fd.c \
		ft_putnbr.c \
		ft_putnbr_fd.c \
		ft_putstr.c \
		ft_putstr_fd.c \
		ft_strcat.c \
		ft_strchr.c \
		ft_strclr.c \
		ft_strcmp.c \
		ft_strcpy.c \
		ft_strdel.c \
		ft_strdup.c \
		ft_strndup.c \
		ft_strequ.c \
		ft_striter.c \
		ft_striteri.c \
		ft_strjoin.c \
		ft_strnjoin.c \
		ft_strlcat.c \
		ft_strlen.c \
		ft_strmap.c \
		ft_strmapi.c \
		ft_strncat.c \
		ft_strncmp.c \
		ft_strncpy.c \
		ft_strnequ.c \
		ft_strnew.c \
		ft_strnstr.c \
		ft_strrchr.c \
		ft_strsplit.c \
		ft_strsplit_len.c \
        ft_strsplit_free.c \
		ft_strstr.c \
		ft_strsub.c \
		ft_strtrim.c \
		ft_tolower.c \
		ft_toupper.c \
		ft_isalnum.c \
		ft_isalpha.c \
		ft_isascii.c \
		ft_isdigit.c \
		ft_isprint.c \
		ft_lstnew.c \
		ft_glstnew.c \
		ft_lstdelone.c \
		ft_lstdel.c \
		ft_lstadd.c \
		ft_lstiter.c \
		ft_lstmap.c \
		ft_swap.c \
		ft_lst_elemcpy.c \
		ft_lstdup.c \
		ft_memrealloc.c \
		ft_digcount_base.c \
		ft_powint.c \
		ft_strnew_chars.c \
		ft_memalloc_chars.c \
		ft_bchars.c\
		ft_numlen.c\
		*ft_create_da.c\
		ft_add_da.c\
		ft_del_da.c\
		ft_resize_da.c\
		*ft_mult_dig_long.c\
		*ft_sum_2_long.c\
		*ft_norm_long_to_base10.c\
		ft_print_da_2_to_16.c\
		get_next_line.c\


OBJ = $(SRC:%.c=%.o)

INC = libft.h \
	  macro.h \
	  get_next_line.h

CC = gcc

CFLAGS = -Wall -Wextra -Werror -c

all: $(NAME)

$(NAME): $(OBJ)
		ar rc $(NAME) $(OBJ)
		ranlib $(NAME)

%.o: %.c
		$(CC) $(CFLAGS)  -I $(INC) $<

clean:
		rm -f $(OBJ)

fclean: clean
		rm -f $(NAME)

re: fclean all
